contact list 기능 구현(recyclerView, itemViewType 적용, itemClick 이벤트 달아놓기)
AndroidJeong/team2_contactapp pull request #7
Opened 2024-04-22 12:08 UTC by neoneoneo123

recyclerView를 구현하기 위해 adapter를 작성하였습니다.

짝, 홀수 번째의 아이템 layout을 달리 적용하기 위해
private val ITEM_TYPE_BASE = 1
private val ITEM_TYPE_REVERSE = 2
이런식으로 아이템을 구분할 수 있는 변수를 만들어 두었습니다.
(onCreateViewHolder, getItemViewType, onBindViewHolder 에서 활용)

또한 ViewHolder도 각각 만들어 총 2개 작성해두었습니다.

---

fragment에서는 onViewCreated() 안에서 recyclerView를 그리고 이벤트를 처리할 수 있게 작성하였습니다.

list fragment에서는 이벤트가 총 3개가 발생할 수 있는데,
1. recyclerView 클릭 시 : 데이터를 bundle로 넘길 수 있게 준비해 두었으며 beginTransaction 부분은 아직 주석처리 해두었습니다. 경우님 코드와 합치고 나서 제대로 작성해보려고 합니다..!
2. FAB 버튼 클릭 시 : dialog fragment를 보여줄 수 있게 show 부분을 작성해두었으나, 아직 현아님 코드와 합치기 전이라 주석처리 하였습니다.
4. 좋아요 버튼 클릭 시 (구현 중)

2024-04-22 12:51 UTC, AndroidJeong approved these changes

2024-04-22 13:14 UTC, DoTheBestMayB requested changes

2024-04-22 13:14 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactListFragment.kt
> +
더미 데이터 삽입은 onCreateView 이전 호출 callback 함수인 onCreate에서 처리하는 것이 좋습니다.

Fragment가 backstack으로 이동할 경우, onDestroyView까지만 호출되어 Fragment는 살아있지만 Fragment View는 파괴됩니다.
이후 Fragment가 다시 보이게 되면 onCreateView가 호출되는데, 이때, dummy 데이터를 이전에 생성했지만, 불필요하게 또 생성해서 넣어주게 됩니다.

현재 ContactManager에서 데이터를 구분하는 고유 id를 통해 중복 삽입을 방지하고 있지만, 만약 List로 입력받은 데이터를 모두 더하는 방식으로 구현되어 있다면, Fragment View가 파괴되고 생성될 때마다, RecyclerView에 표시되는 데이터가 계속 늘어날 것입니다.

2024-04-22 13:14 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactListFragment.kt
> +//                    .commit()
FragmentContainerView를 사용하지 않는 상황에서 새로운 Fragment를 생성하는 방법을 검색해보니 아래 글이 나오네요.

https://stackoverflow.com/a/66395876/11722881
https://stackoverflow.com/a/54620613/11722881

그런데 ViewPager에 있는 Fragment에서 다른 Fragment를 호출하는 것이 맞는 행위인지는 튜터 님에게 질문을 통해 확인이 필요할 것 같습니다.

이와 관련된 내용에 대해 알게 되시면 공유해주세요😄

2024-04-22 13:14 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactAdapter.kt
> +    var itemClick: ItemClick? = null
itemClick을 non-nullalbe로 선언할 수 있도록 변경해보시면 어떨까요?😀

2024-04-22 13:14 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactAdapter.kt
> +class ContactAdapter(private val contacts: List<ContactInfo>) :
contacts가 val + immutable로 선언되어 있다보니, 한 번 데이터를 입력하면 변경할 수 없어요.
그래서 연락처가 새롭게 추가돼도 RecyclerView에 표시할 수 없을 것 같아요.

2024-04-22 13:14 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_contact_list.xml
> +            app:layout_constraintTop_toTopOf="parent">
현재 Layout의 depth가 3입니다!! depth를 1로 줄여서 ConstraintLayout의 장점을 활용해보는 건 어떨까요?

2024-04-23 02:20 UTC, neoneoneo123 commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactListFragment.kt
> +
코멘트 감사합니다~

이번에 준영님께서 만들어주신 기기 내의 연락처를 가져와 사용할 때에는 onCreate에서 처리할 수 있게끔 수정하겠습니다.

2024-04-23 02:26 UTC, neoneoneo123 commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactAdapter.kt
> +    var itemClick: ItemClick? = null
lateinit var itemClick: ItemClick

lateinit을 사용하여 처음부터 null을 넣어서 사용하지 않게끔 수정했습니다 ^_^~

2024-04-23 02:35 UTC, neoneoneo123 commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactAdapter.kt
> +class ContactAdapter(private val contacts: List<ContactInfo>) :
넵 mutableList로 변경하고, var로 선언하여 데이터의 변경 사항을 적용할 수 있도록 수정하였습니다.

class ContactAdapter(private var contacts: MutableList<ContactInfo>)

감샇합니다~

2024-04-23 02:36 UTC, neoneoneo123 commented on app/src/main/res/layout/fragment_contact_list.xml
> +            app:layout_constraintTop_toTopOf="parent">
ㅎㅎ.. 노력 해볼게요..

2024-04-23 02:37 UTC, neoneoneo123 commented on app/src/main/java/com/nbc/two_of_us/presentation/contact/ContactListFragment.kt
> +//                    .commit()
이 부분은 나중에 경우님, 현아님 코드와 합칠 때 고려해보겠습니다..!
지금은 일단 다른 작업들 먼저 하고 있을게요~

2024-04-23 02:51 UTC, neoneoneo123 commented on app/src/main/res/layout/fragment_contact_list.xml
> +            app:layout_constraintTop_toTopOf="parent">
![image](https://github.com/AndroidJeong/team2_contactapp/assets/128209823/aff98c9a-7cc7-48e8-8440-2765c433577d)

depth를 좀 줄여봤습니다..!
다만, header의 경우에는 background 색상을 지정해주기 위해 frameLayout을 사용하였습니다.. ㅎㅎㅎ

2024-04-24 01:33 UTC, DoTheBestMayB approved these changes

2024-04-24 01:37 UTC, merged